### ISSUE TITLE
调试vite过程中遇到问题，请帮忙看下是怎么回事

### ISSUE THREAD

**Issue by casey2024** [vitejs/docs-cn#1047]
client.ts:18 [vite] connecting...
client.ts:150 [vite] connected.
virtual:@vite-plugin-checker-runtime:7727 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'event')
    at onMessage (virtual:@vite-plugin-checker-runtime:7727:18)
    at virtual:@vite-plugin-checker-runtime:7744:11
    at client.ts:285:25
    at Array.forEach (<anonymous>)
    at notifyListeners (client.ts:285:9)
    at handleMessage (client.ts:224:7)
    at WebSocket.<anonymous> (client.ts:91:5)

**Comment by waynzh** [comment]
# Vite 使用问题相关 issue 统一处理
感谢您对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 区，请不要在此提交关于 Vite 使用的问题或报 Bug**。相关问题请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues) 提交最小复现以解决问题。

感谢你的配合。
