### ISSUE TITLE
vite+ssr+react按需加载antd错误

### ISSUE THREAD

**Issue by Marber-seven** [vitejs/docs-cn#319]
vite.config.js文件配置

styleImport({
      libs: [{
        libraryName: 'antd',
        esModule: true,
        resolveStyle: (name) => {
          return `antd/es/${name}/style/index`;
        },
      }]
    })
    vitePluginImp({
      libList: [
        {
          libName: "antd",
          esModule: true,
          style: (name) => `antd/es/${name}/style/index.less`,
          // style: (name) => `antd/lib/${name}/style/index.less`,
        },
      ],
    })

几种方式都试了不得行，请问下是怎么回事啊？

第一个报错内容

TypeError: Cannot set properties of undefined (setting 'isSelfAccepting')
    at ModuleGraph.updateModuleInfo (E:\app\bot-group-web\node_modules\_vite@2.6.14@vite\dist\node\chunks\dep-e0fe87f8.js:57164:29)
    at TransformContext.transform (E:\app\bot-group-web\node_modules\_vite@2.6.14@vite\dist\node\chunks\dep-e0fe87f8.js:67531:57)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (E:\app\bot-group-web\node_modules\_vite@2.6.14@vite\dist\node\chunks\dep-e0fe87f8.js:42396:30)
    at async doTransform (E:\app\bot-group-web\node_modules\_vite@2.6.14@vite\dist\node\chunks\dep-e0fe87f8.js:56801:29)

第二个报错内容

下午10:42:20 [vite] Error when evaluating SSR module /node_modules/_react-dom@17.0.2@react-dom/server.js?v=273e34bc:
ReferenceError: module is not defined
    at /node_modules/_react-dom@17.0.2@react-dom/server.js?v=273e34bc:3:1
    at instantiateModule (E:\app\bot-group-web\node_modules\_vite@2.6.14@vite\dist\node\chunks\dep-e0fe87f8.js:66544:15)

**Comment by ShenQingchuan** [comment]
## Vite 使用问题相关 issue 统一处理

首先感谢你对 Vite 的支持，但这里是 Vite 官方中文文档的翻译项目相关 issue 的提交站。

这里不是 Vite 的中文社区，请不要在此提交关于 Vite 使用的问题或报 Bug。，请移步 Vite 主仓库 issue 区。

感谢你的配合。
