### ISSUE TITLE
yarn build 提示 return this._head?.value;

### ISSUE THREAD

**Issue by tguzi** [vitejs/docs-cn#362]
/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/wuqingfu/Desktop/demo/devops/front/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
error Command failed with exit code 1.

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
